// flow-typed signature: 8163732a036df5849e0b628471f98442
// flow-typed version: <<STUB>>/react-ui-cards_v1.4.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ui-cards'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ui-cards' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ui-cards/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ui-cards/bundle.js' {
  declare module.exports: $Exports<'react-ui-cards/bundle'>;
}
declare module 'react-ui-cards/index' {
  declare module.exports: $Exports<'react-ui-cards'>;
}
declare module 'react-ui-cards/index.js' {
  declare module.exports: $Exports<'react-ui-cards'>;
}
